name: Daily TB Refill Alert
on:
  schedule:
    - cron: '0 6 * * *' # 6:00 AM GMT (Accra Time)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Pandas
        run: pip install pandas
      - name: Process
        id: checker
        run: python refill_checker.py
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "TB Refill Alert: Today & Tomorrow"
          to: user1@email.com, user2@email.com # REPLACE WITH YOUR EMAILS
          from: TB Clinic Monitor
          body: |
            Daily Report for ${{ github.event.repository.updated_at }}:
            
            ${{ steps.checker.outputs.report }}
